name:                nsc-lib
version:             0.1.0.0
github:              "mesabloo/n-star"
license:             BSD3
author:              "Mesabloo"
copyright:           "2020 Mesabloo"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mesabloo/n-star#readme>

dependencies:
- base >= 4.7 && < 5
- diagnose

library:
  source-dirs: src

default-extensions: !include "default-extensions.txt"

executables:
  nsc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nsc-lib

tests:
  n-star-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - n-star
