resolver: lts-16.10

packages:
- .
- ./lib/nsc-core
- ./lib/nsc-parser

extra-deps:
- git: https://github.com/mesabloo/diagnose.git
  commit: caa37da06519711d8831df34c577be3c897bc111


nix:
    shell-file: shell.nix
