resolver: lts-16.10

packages:
- .
- ./lib/nsc-core
- ./lib/nsc-parser
- ./lib/nsc-typechecker
- ./lib/nsc-pretty
- ./lib/nsc-flags
- ./lib/nsc-codegen
- ./lib/elfgen
- ./lib/nsc-branchchecker

extra-deps:
- git: https://github.com/mesabloo/diagnose.git
  commit: cf64944304c07a3fef771739ab46ffc8fe4ee399


nix:
    shell-file: stack-shell.nix
