resolver: lts-16.10

packages:
- .
- ./lib/nsc-core
- ./lib/nsc-parser
- ./lib/nsc-typechecker
- ./lib/nsc-pretty

extra-deps:
- git: https://github.com/mesabloo/diagnose.git
  commit: fbb1577c6dfeb4d526556a8b65d47394ad7b367d


nix:
    shell-file: stack-shell.nix
