resolver: lts-16.10

packages:
- .
- ./lib/nsc-core
- ./lib/nsc-parser
- ./lib/nsc-typechecker

extra-deps:
- git: https://github.com/mesabloo/diagnose.git
  commit: e977c7ba6aa8709a0658daec53dd6b08dadeba8b


nix:
    shell-file: stack-shell.nix
