resolver: lts-16.10

packages:
- .
- ./lib/nsc-core
- ./lib/nsc-parser
- ./lib/nsc-typechecker

extra-deps:
- git: https://github.com/mesabloo/diagnose.git
  commit: a5d5c25d8b563dfa03cc1424fe30b0d5517c18ac


nix:
    shell-file: stack-shell.nix
