resolver: lts-16.10

packages:
- .
- ./lib/nsc-core
- ./lib/nsc-parser
- ./lib/nsc-typechecker

extra-deps:
- git: https://github.com/mesabloo/diagnose.git
  commit: 3937b074c9bfaca0b26cd63bc75f791895ee59a4


nix:
    shell-file: stack-shell.nix
