resolver: lts-16.10

packages:
- .
- ./lib/nsc-core
- ./lib/nsc-parser
- ./lib/nsc-typechecker

extra-deps:
- git: https://github.com/mesabloo/diagnose.git
  commit: a4d52a8b1cb9cb298a1f1cc01863a58bfe211df2


nix:
    shell-file: stack-shell.nix
