resolver: lts-16.10

packages:
- .
- ./lib/nsc-core
- ./lib/nsc-parser
- ./lib/nsc-typechecker
- ./lib/nsc-pretty
- ./lib/nsc-flags
- ./lib/nsc-codegen
- ./lib/elfgen

extra-deps:
- git: https://github.com/mesabloo/diagnose.git
  commit: c6223edb04c952eda4794ce9fc99817f1bfc66c6


nix:
    shell-file: stack-shell.nix
