resolver: lts-16.10

packages:
- .
- ./lib/nsc-core
- ./lib/nsc-parser

extra-deps:
- git: https://github.com/mesabloo/diagnose.git
  commit: 7578416b725213398bfaa7603013cfd6dc5695d5


nix:
    shell-file: shell.nix
