resolver: lts-16.10

packages:
- .
- ./lib/nsc-core
- ./lib/nsc-parser
- ./lib/nsc-typechecker
- ./lib/nsc-pretty
- ./lib/nsc-flags
- ./lib/nsc-codegen
- ./lib/elfgen
- ./lib/nsc-branchchecker

extra-deps:
- git: https://github.com/mesabloo/diagnose.git
  commit: 559ade8c484aa0c14b484040d4c8ed5fe216efdf


nix:
    shell-file: stack-shell.nix
